package user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/bishal-dd/go-server/graph/loader"
	"github.com/bishal-dd/go-server/graph/model"
)
type UserResolver struct{}

func (r *UserResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

func (r *UserResolver) Users(ctx context.Context) ([]*model.User, error) {
	return []*model.User{}, nil
}

func (r *UserResolver) User(ctx context.Context, id string) (*model.User, error) {
	loaders := loader.For(ctx)
	fmt.Println(loaders)
	return loaders.UserLoader.Load(ctx, id)
}
