package receipt

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/bishal-dd/go-server/graph"
	"github.com/bishal-dd/go-server/graph/model"
)

type ReceiptResolver struct{}


// CreateReceipt is the resolver for the createReceipt field.
func (r *ReceiptResolver) CreateReceipt(ctx context.Context, input model.NewReceipt) (*model.Receipt, error) {
	panic(fmt.Errorf("not implemented: CreateReceipt - createReceipt"))
}


// Receipts is the resolver for the receipts field.
func (r *ReceiptResolver) Receipts(ctx context.Context) ([]*model.Receipt, error) {
    return []*model.Receipt{}, nil
}

// User is the resolver for the user field.
func (r *receiptResolver) User(ctx context.Context, obj *model.Receipt) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Receipt returns graph.ReceiptResolver implementation.
func (r *ReceiptResolver) Receipt() graph.ReceiptResolver { return &receiptResolver{r} }

type receiptResolver struct{ *ReceiptResolver }
